### ISSUE TITLE
socket.io Javascript error

### ISSUE THREAD

**Issue by windows10luke** [jrussellfreelance/nginx-config-editor#6]
When trying to load Nginx Config Editor on my server, some of the page loads, but the editing part is completely blank and does nothing. Also, all the Nginx control buttons don't do anything either. Upon inspecting the page, I found that it is failing to load the socket.io-1.4.5.js file is failing to load with an error code of 404. Also, when trying to load the link, [https://cdn.socket.io/socket.io-1.4.5.js](url) to the Javascript file, I get the following error message: The deployment could not be found on Vercel. It appears that either the file is deleted from the CDN or the server won't serve it for some reason. I might also add that the entire editor was working fine about a week ago, and then suddenly failed with these issues. Any help with this would be appreciated. Thanks!

**Comment by jrussellfreelance** [comment]
@windows10luke Sorry for the delay on seeing this issue!  I just pulled in some changes that someone else added.  I saw that he made a bunch of CDN updates, so you might try pulling the latest to see if his changes fix it.

If that specific CDN is not working, I will open up the code and fix it myself.

Thanks for posting your issue!

**Comment by windows10luke** [comment]
Sorry for my delayed response. Soon after I opened this issue, it appeared that the CDN that was previously having issues suddenly started working and has been working ever since. Thanks for looking into this issue!
