### ISSUE TITLE
Incorrect Dockerfile

### ISSUE THREAD

**Issue by pkeech** [jrussellfreelance/nginx-config-editor#8]
Simple typo in your Dockerfile causing the docker file not to build.

On line 7, the `npm` dependency is missing the `-y` tag.

**Comment by jrussellfreelance** [comment]
Haha thanks for pointing this out! I actually haven't touched the Dockerfile in quite a while so I am glad to know it is still functional on some level!

**Comment by pkeech** [comment]
No problem. I'm glad it was an easy catch and fix.
